// 3.58 pm logic has been generated by self 

class Demo{
	public static void main(String[]args){
		int arr [] ={1,45,17,18,8};
		int max=0;
		
		for(int i=0;i<arr.length;i++){
			if(arr[i]>max){
				max=arr[i];
			}
		}	
		int second_max=0;		

		for(int i=0;i<arr.length;i++){
			if(arr[i]>second_max && arr[i]<max){
				second_max=arr[i];
			}
		}
		System.out.println(second_max);
	}
}