// 3.58 pm logic has been generated by self 

class Demo{
	public static void main(String[]args){
		int arr [] ={2,5,7,5,10};
		int min=10;
		
		for(int i=0;i<arr.length;i++){
			if(arr[i]<min){
				min=arr[i];
			}
		}	
		int second_min=10;		

		for(int i=0;i<arr.length;i++){
			if(arr[i]<second_min && arr[i]>min){
				second_min=arr[i];
			}
		}
		System.out.println(second_min);
	}
}